### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [borodust/cl-muth#2]
Building with SBCL 2.1.10 / ASDF 3.3.5 for quicklisp dist creation.

Trying to build commit id 4a91da2707e4fdc2d54924a8a1222dcf62c78389

*cl-muth* fails to build with the following error:

```
; caught WARNING:
;   * is not permitted as an argument to the FUNCTION type specifier
; 
; caught WARNING:
;   * is not permitted as an argument to the FUNCTION type specifier
...
Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING {1001C08103}>: COMPILE-FILE-ERROR while compiling #<CL-SOURCE-FILE "cl-muth" "guarded-reference">

```

*cl-muth/tests* fails to build because of a failure in  _cl-muth_.

[Full log here](http://report.quicklisp.org/2021-11-02/failure-report/cl-muth.html)

**Comment by borodust** [comment]
Thanks! I'll look into it.

**Comment by borodust** [comment]
Fixed in https://github.com/borodust/cl-muth/commit/40b14a91097fea87b835ab7d83dfa6c914045021

**Comment by xach** [comment]
Sorry, this does not fix it for me.
