### ISSUE TITLE
Remove global package nicknames

### ISSUE THREAD

**Issue by zen-wq** [borodust/cl-muth#3]
I know the package is in Quicklisp already but it's not too late since there are not too many users yet.

Global package nicknames is a recipe for disaster, especially short or common ones like "mt" or "flow". Quicklisp already had a problem with two base64 codec packages using the same nickname which made it impossible to load systems depending on different base64 libraries into the same system.

It's two years since both SBCL and CCL (which look like the main implementations you're targeting) got package-local-nicknames so if a user of your library wants to save some typing they'll just make a local nickname for it. Without any risk of collision.

It's an issue for https://github.com/borodust/cl-flow too.

**Comment by borodust** [comment]
What's in quicklisp stays in quicklisp.

I understand your concern and there already were clashes with flow in particular, but I'm not going to rename what is already in QL.
